### ISSUE TITLE
Custom Tank Not Giving Correct Output

### ISSUE THREAD

**Issue by pspeirs** [bartbutenaers/node-red-contrib-tank-volume#3]
The custom configuration gives a correct output for the first run, subsequent calls multiply the outputs by 1000 each iteration.  This also happens when using the "sample" custom tank configuration.

{ totalVolume: 500, filledVolume: 250, emptyVolume: 250, usableVolume: 0, usableFilledVolume: 0 … }
11/21/2021, 11:00:25 AMnode: 8806beda52b0580c

msg.payload : Object
{ totalVolume: 500000, filledVolume: 250000, emptyVolume: 250000, usableVolume: 0, usableFilledVolume: 0 … }
11/21/2021, 11:00:27 AMnode: 8806beda52b0580c

msg.payload : Object
{ totalVolume: 500000000, filledVolume: 250000000, emptyVolume: 250000000, usableVolume: 0, usableFilledVolume: 0 … }

**Comment by bartbutenaers** [comment]
Hi @pspeirs,
Thanks for reporting this issue!
It seems you are the first one using this feature ...

I have fixed it now on Github.  Would be nice if you could install this node directly from Github, and let me know whether it works now correctly before I publish it on NPM.  You can install it like this, from within your .node-red folder:
```
npm install bartbutenaers/node-red-contrib-tank-volume
```
Note that I have also updated the custom table example flow (both in the readme and in Node-RED's Import menu), because the topLimit was 80 and the bottomLimit was 20.  Which is not correct, because the top limit is measured from the top of the tank...

Thanks again!
Bart

**Comment by pspeirs** [comment]
To be honest, I'm not sure how to bring up a console.  I'm using code-red as an addin to Home Assistant, still a noob

**Comment by bartbutenaers** [comment]
That is a pity...  Had hoped someone could test it before publishing it.
Anyway version ***1.0.2*** is now available in the palette:

![image](https://user-images.githubusercontent.com/14224149/142756277-73d630fe-92de-433e-b94f-f6594a17035d.png)

**Comment by pspeirs** [comment]
OK, quick test and it seems to be working a lot better, displaying the correct values.  Many thanks for the fast turn around.

**Comment by bartbutenaers** [comment]
You are welcome.
Don't hesitate to report other issues, because it seems you are my first customer for this one ;-)
