### ISSUE TITLE
Wrong volume on Frustum

### ISSUE THREAD

**Issue by Diddlik** [bartbutenaers/node-red-contrib-tank-volume#4]
I have defined a tank in the form of a frustrum.
It has the following dimensions:

Height: 118
Diam Top: 60
Diam Bot: 40
Measure: Height above fluid
Top Limit 114

On input of height 116cm, that means it es almost empty. I get a filled volume about 150 L.
![grafik](https://user-images.githubusercontent.com/6010713/145692227-898ecd73-779e-4482-9bc9-4e7ada9ae57f.png)

**Comment by bartbutenaers** [comment]
Hi @Diddlik,

Thanks for testing this node!
I now remember that indeed I had some issues - at the time being - to calculate the frustrum.
But seems it was not solved entirely.

Some of my calculations are based on the formula's from Hanna Pamula, which you can find in the [omnicalculator](https://www.omnicalculator.com/construction/tank-volume).  When I enter your data over there, it indeed calculates a very low partially filled volume.  So the result on the omnicalculator site is correct, since your tank is almost empty.

But when I enter your data values manually in the formulas, then I get a very high volume (similar to my node):

![image](https://user-images.githubusercontent.com/14224149/145704642-b3323d44-45e2-4057-a33d-9cd243420144.png)

Somewhere I am misinterpreting Hanna's formulas, but I don't see at first sight what I am doing wrong.  

So I have send her a mail with your example.  Hopefully she responds soon.  
I will update this issue as soon as I have an update...

Bart

**Comment by Diddlik** [comment]
I think you should use not cone_hight at the end, instead of them filled_hight.

**Comment by bartbutenaers** [comment]
Yes you are right!
And meanwhile Hanna has been so kind to confirm this also!
I already did use the filled heights for frustrums when radiusTop < radiusBottom.
Not sure why I did it only in that case.  Too long ago for my old brain...

Anyway I have fixed it on Github.
Could you please install my fix directly from Github, by following command (from within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-tank-volume
```
If it works fine for you, then I will publish it on NPM.

BTW. I see that your ***top limit*** is 114.  When you have a look at the drawing on the [Usable volume and limits](https://github.com/bartbutenaers/node-red-contrib-tank-volume#usable-volume-and-limits) section on my readme page, you will see that the top limit is measured from the top of the tank.  Not from the bottom.  Not sure if that is clear.  Perhaps I should put that in bold, because I have also made the mistake in the past to enter the wrong distance (i.e. measured from the bottom of the tank)...

**Comment by Diddlik** [comment]
Top Limit here is wrong. In nodered is 14, only here I wrote wrong value.

**Comment by Diddlik** [comment]
with filled heights it works fine!

**Comment by Diddlik** [comment]
![grafik](https://user-images.githubusercontent.com/6010713/145711195-20c16808-4919-4123-ad2d-567081910478.png)

**Comment by bartbutenaers** [comment]
Ok thanks for testing!  So did I understand correctly that it is ready to publish this fix on npm?

**Comment by Diddlik** [comment]
Yes, I would say it seems to work fine.

**Comment by bartbutenaers** [comment]
Hi @Diddlik,

Version ***1.0.3*** is now available:

![image](https://user-images.githubusercontent.com/14224149/145731816-1c22a23b-4981-4bf0-9961-ff13ef2756c4.png)
